### ISSUE TITLE
Select A License

### ISSUE THREAD

**Issue by akubera** [oktal/result#1]
Currently there is no mention of how you wish to license this software. Therefore, _technically_ (under some interpretations), it is in violation of copyright law for others to make a copy.

I'd think it'd be nice for the community if you explicitly set the license.

For a single-file header, I'd recommend a very permissive license, such as the [UNLICENSE](http://unlicense.org) or [MIT](https://opensource.org/licenses/MIT).

The project looks good, thanks!

**Comment by oktal** [comment]
Hello,

Done, the project is now Apache-licensed
